[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "pynamit"
dynamic = ["version"]
dependencies = [
    "cupy",
    "pandas",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
