[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "pynamit"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "apexpy",
    "dipole @ git+https://github.com/klaundal/dipole.git@main",
    "numpy>=2.0",
    "packaging",
    "pandas",
    "ppigrf",
    "scipy",
    "xarray",
]

[project.optional-dependencies]
jax = [
    "jax>=0.4.26",
]
gui = [
    "cartopy",
    "h5py",
    "matplotlib",
    "netCDF4",
    "panel",
    "pillow",
    "polplot @ git+https://github.com/klaundal/polplot.git@main",
    "zarr",
]
inputs = [
    "lompe @ git+https://github.com/klaundal/lompe.git@main",
    "pyamps",
    "pyhwm2014 @ git+https://github.com/rilma/pyHWM14.git@main",
]

[project.scripts]
pynamit-gui = "pynamit.visualization.gui:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]

[tool.ruff]
src = ["src", "tests", "scripts"]
extend-exclude = ["__init__.py", "notebooks/", "scripts/simulation/legacy/"]
line-length = 99

[tool.ruff.lint]
extend-select = ["B", "E", "I", "UP", "W", "D"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
skip-magic-trailing-comma = true
