"""Induction-system assembly and solver helpers."""

from .operator_utils import (
    build_linear_map,
    cached_dense_builder,
    coerce_dense_operator_matrix,
)
from .operators import BlockCoupledOperator, ResistivityTensorOperator
from .poloidal import PoloidalSystemMatrices
from .poloidal_closure import PoloidalClosureProjector, RMCouplingOperators
from .poloidal_solver import PoloidalSolver
from .rm_boundary import MagneticRMBoundaryOperators
from .radial_shell_response import (
    CallableRadialShellResponseModel,
    CurrentContinuityExteriorToroidalUpdateModel,
    ColumnSolveKnownSourceTraceModel,
    EquivalentNonlocalExteriorToroidalUpdateModel,
    EquivalentNonlocalRadialShellResponseModel,
    ExteriorToroidalScalarRadialResponseModel,
    ExteriorToroidalUpdateModel,
    ExteriorToroidalUpdateKnownSourceTraceModel,
    FilteredKnownSourceTraceModel,
    FrozenConductanceIncrementalKnownElectricRadialResponseModel,
    GapCoenergyBlocks,
    RadialShellCondensedOperators,
    HarmonicShellElectricTraceModel,
    HarmonicPoloidalSideTraceModel,
    CurrentFirstParticularPlusHarmonicKnownSourceTraceModel,
    HomogeneousOuterMagneticBoundaryColumnSolveKnownSourceTraceModel,
    InductivePlusHarmonicKnownSourceTraceModel,
    IncrementalIdealityCorrectedExteriorToroidalUpdateModel,
    AdditiveKnownSourceTraceModel,
    KnownSourceTraceModel,
    KnownSourceOperatorKnownSourceTraceModel,
    NonlocalShellElectricRadialResponseModel,
    PFACNonlocalRadialShellResponseModel,
    PoloidalSideTraceKnownSourceTraceModel,
    PoloidalSideTraceModel,
    ProjectedTangentialSecondTraceModel,
    QTraceKnownSourceRadialResponseModel,
    RadialShellResponseModel,
    RMToroidalBoundaryUpdateModel,
    SchurComplementGapKnownSourceTraceModel,
    ShellCurrentDrivenKnownElectricRadialResponseModel,
    ShellElectricTraceModel,
    ShellElectricDifferenceKnownSourceTraceModel,
    ShellCurrentContinuityKnownElectricRadialResponseModel,
    ThinSheetCurrentContinuityKnownShellCurrentSourceModel,
    build_gap_coenergy_blocks_from_condensed_operators,
    build_known_source_operator_from_q_trace,
    build_gap_coenergy_condensed_operators_from_blocks,
    build_q_trace_operator_from_known_source_model,
    build_q_trace_operator_from_exterior_update_model,
    build_q_trace_operator_from_poloidal_side_trace,
    build_radial_shell_rhs_from_trace_operator,
    build_radial_shell_rhs_from_q_trace_operator,
    build_projected_tangential_omitted_rhs_operator,
)
from .toroidal import ToroidalSystemMatrices
from .toroidal_closure import ToroidalClosureProjector
from .toroidal_solver import ToroidalSolver

__all__ = [
    "BlockCoupledOperator",
    "ResistivityTensorOperator",
    "MagneticRMBoundaryOperators",
    "PoloidalSystemMatrices",
    "PoloidalClosureProjector",
    "RMCouplingOperators",
    "PoloidalSolver",
    "RadialShellResponseModel",
    "ShellElectricTraceModel",
    "KnownSourceTraceModel",
    "KnownSourceOperatorKnownSourceTraceModel",
    "PoloidalSideTraceModel",
    "PoloidalSideTraceKnownSourceTraceModel",
    "HarmonicShellElectricTraceModel",
    "HarmonicPoloidalSideTraceModel",
    "HomogeneousOuterMagneticBoundaryColumnSolveKnownSourceTraceModel",
    "ShellElectricDifferenceKnownSourceTraceModel",
    "ProjectedTangentialSecondTraceModel",
    "ExteriorToroidalUpdateModel",
    "ExteriorToroidalUpdateKnownSourceTraceModel",
    "FilteredKnownSourceTraceModel",
    "FrozenConductanceIncrementalKnownElectricRadialResponseModel",
    "GapCoenergyBlocks",
    "RadialShellCondensedOperators",
    "ShellCurrentDrivenKnownElectricRadialResponseModel",
    "ThinSheetCurrentContinuityKnownShellCurrentSourceModel",
    "AdditiveKnownSourceTraceModel",
    "CurrentFirstParticularPlusHarmonicKnownSourceTraceModel",
    "build_gap_coenergy_blocks_from_condensed_operators",
    "ExteriorToroidalScalarRadialResponseModel",
    "CurrentContinuityExteriorToroidalUpdateModel",
    "ColumnSolveKnownSourceTraceModel",
    "EquivalentNonlocalExteriorToroidalUpdateModel",
    "InductivePlusHarmonicKnownSourceTraceModel",
    "RMToroidalBoundaryUpdateModel",
    "SchurComplementGapKnownSourceTraceModel",
    "IncrementalIdealityCorrectedExteriorToroidalUpdateModel",
    "CallableRadialShellResponseModel",
    "EquivalentNonlocalRadialShellResponseModel",
    "QTraceKnownSourceRadialResponseModel",
    "NonlocalShellElectricRadialResponseModel",
    "PFACNonlocalRadialShellResponseModel",
    "ShellCurrentContinuityKnownElectricRadialResponseModel",
    "build_known_source_operator_from_q_trace",
    "build_gap_coenergy_condensed_operators_from_blocks",
    "build_q_trace_operator_from_known_source_model",
    "build_q_trace_operator_from_exterior_update_model",
    "build_q_trace_operator_from_poloidal_side_trace",
    "build_radial_shell_rhs_from_trace_operator",
    "build_radial_shell_rhs_from_q_trace_operator",
    "build_projected_tangential_omitted_rhs_operator",
    "ToroidalSystemMatrices",
    "ToroidalClosureProjector",
    "ToroidalSolver",
    "build_linear_map",
    "cached_dense_builder",
    "coerce_dense_operator_matrix",
]
