name: 'Build, Test, and Deploy'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    container: ghcr.io/dynamit-uib/pynamit:x86_64-2025-02-11
    defaults:
      run:
        shell: 'bash -leo pipefail {0}'
    steps:
      - name: Install Ruff and Sphinx
        run: 'pip install ruff sphinx sphinx-rtd-theme myst-parser'
      - name: Check out PynaMIT repository
        uses: actions/checkout@v4
      - name: Lint PynaMIT code
        run: 'ruff check'
      - name: Build documentation
        run: 'sphinx-apidoc -o docs/source src && sphinx-build -b html docs/source docs/build'
      - name: Install PynaMIT
        run: 'pip install .'
      - name: Run PynaMIT tests
        run: 'pytest -v'
      - name: Upload documentation artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-docs.outputs.page_url }}
    steps:
      - name: Deploy documentation to GitHub Pages
        id: deploy-docs
        uses: actions/deploy-pages@v4