name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ghcr.io/dynamit-uib/pynamit:v0.1

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: '/PynaMIT'

      - name: Install PynaMIT
        run: 'pip install /PynaMIT'

      # Add your test execution steps here
      - name: Run tests
        run: 'pytest -v /PynaMIT/tests'